### ISSUE TITLE
No matching distribution found for get==2019.4.13

### ISSUE THREAD

**Issue by KumWeng** [ElasticBottle/Badminton_Avalability_checker#5]
Hello there,
I had issues when I run the requirement file, would you be able to assist with this?
Appreciate it, Thank you!

Collecting altgraph==0.17
  Using cached altgraph-0.17-py2.py3-none-any.whl (21 kB)
Collecting appdirs==1.4.3
  Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting astroid==2.3.3
  Using cached astroid-2.3.3-py3-none-any.whl (205 kB)
Collecting attrs==19.3.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting beautifulsoup4==4.8.2
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Collecting black==19.10b0
  Using cached black-19.10b0-py36-none-any.whl (97 kB)
Collecting certifi==2019.11.28
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting Click==7.0
  Using cached Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting future==0.18.2
  Using cached future-0.18.2.tar.gz (829 kB)
ERROR: Could not find a version that satisfies the requirement get==2019.4.13 (from versions: none)
ERROR: No matching distribution found for get==2019.4.13

**Comment by ElasticBottle** [comment]
Hi Buddy, not too sure about this one, let me get back to you on it when I do find out!
